# serverless.yml
service: affordability-api-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  
functions:
  create_check:
    handler: handler.createCheck
    events:
      - httpApi:
          path: /checks
          method: post
  validate_check:
    handler: handler.validateCheck
    events:
      - httpApi:
          path: /checks/{token}
          method: get